version: '3'
services:
    app:
        build: .
        ports:
            - '3000:3000'
        environment:
            DATABASE_URL: postgres://user:pass1234@db:5432/your_db_name
        depends_on:
            - db
    db:
        image: postgres
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: pass1234
            POSTGRES_DB: your_db_name
        ports:
            - '5432:5432'
        volumes:
            - db-data:/var/lib/postgresql/data
volumes:
    db-data:
